version: "3"

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_net
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - redis_net
    environment:
      REDIS_ARGS: "--requirepass root"

networks:
  rabbitmq_net:
    driver: bridge
  redis_net:
    driver: bridge
