version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rabbitmq-net
      - redis-net
    volumes:
      - ./api:/app
      - ./common:/app/common
    ports:
      - 5000:5000

  fetcher:
    build:
      context: .
      dockerfile: ./fetcher/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rabbitmq-net
    volumes:
      - ./fetcher:/app
      - ./common:/app/common

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "rabbitmq"
    ports:
      - :5672
      - 15672:15672
    networks:
      - rabbitmq-net
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - :6379
      - 8001:8001
    networks:
      - redis-net
    environment:
      REDIS_ARGS: "--requirepass root"

networks:
  redis-net:
    driver: bridge
  rabbitmq-net:
    driver: bridge
